# this flie was generated by compiler explorer using mips-gcc 15.2.0
main:
 addiu	sp,sp,-48
 sw	ra,44(sp)
 sw	s8,40(sp)
 move	s8,sp
 li	v0,5
 sw	v0,24(s8)
 li	v0,15
 sw	v0,28(s8)
 lw	a1,28(s8)
 lw	a0,24(s8)
 jal	0 <main>
    R_MIPS_26 sum
 nop
 sw	v0,32(s8)
 b	34 <main+0x34>
 nop
sum:
 addiu	sp,sp,-8
 sw	s8,4(sp)
 move	s8,sp
 sw	a0,8(s8)
 sw	a1,12(s8)
 lw	v1,8(s8)
 lw	v0,12(s8)
 nop
 addu	v0,v1,v0
 move	sp,s8
 lw	s8,4(sp)
 addiu	sp,sp,8
 jr	ra
 nop
 ...